config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'index#show'
  devise_for :members, :controllers => { :omniauth_callbacks => "members/omniauth_callbacks" }
  devise_scope :member do
    get '/members/sign_out' => 'devise/sessions#destroy'
  end

  # For Member Pages
  resources :members, :only => [:show, :edit, :update]

  resources :organizations, :only => [:show]
  resources :organizations, :only => [:index] do
    resources :member_organization_association
    resources :lunch, only: %i[index create show] do
      resources :groups, only: %i[show edit update]
    end
  end

  # For Organization Admin Panel
  scope :organization_admin do
    resources :organizations, :only => [:create, :new, :edit, :update]
  end
end

app/models/member_organization_association.rb
class MemberOrganizationAssociation < ApplicationRecord
  belongs_to :member
  belongs_to :organization

  validates :member_id, presence: true, numericality: true
  validates :organization_id, presence: true, numericality: true
  validates :organizer, inclusion: { in: [true, false] }
end

app/controllers/member_organization_association_controller.rb
class MemberOrganizationAssociationController < ApplicationController
  before_action :load_resources, only: %i[index new create]
  def index; end

  def create
    @association = MemberOrganizationAssociation.create(create_association_params)
    redirect_to action: 'new', notice: 'Complete!!'
  end

  def new
    @searched_members = Member.search(params[:search])
  end

  private

  def load_resources
    @organization = Organization.find(params[:organization_id])
    @members = Member.organization_members(@organization.id)
  end

  def create_association_params
    params.permit(:member_id, :organization_id)
  end
end

app/helpers/member_organization_association_helper.rb
module MemberOrganizationAssociationHelper
end

app/views/member_organization_association/index.html.slim
= render :partial => 'layouts/header'
doctype html
html[lang="en"]
  body.animsition
    section.bg-title-page.flex-c-m.p-t-160.p-b-80.p-l-15.p-r-15
      - if @organization.image_url.present?
        = image_tag(@organization.image_url.url)
      - else
        = image_tag("default.png")
    h3.tit5.t-center.m-t-2
      = @organization.name
    .section-gallery.p-t-118.p-b-100
      .wrap-gallery.isotope-grid.flex-w.p-l-25.p-r-25
        - @members.each do |member|
          .item-gallery.isotope-item.bo-rad-10.hov-img-zoom.events.guests
            - if member.image_url.present?
              = image_tag(member.image_url)
            - else
              = image_tag("default.png")
            .overlay-item-gallery.trans-0-4.flex-c-m
              = link_to'', member_path(member), class: "btn-show-gallery flex-c-m fa fa-search"
      = link_to "Invite Members", new_organization_member_organization_association_path(@organization), class: "btn3 flex-c-m size31 txt11 trans-0-4", style: "margin: auto;"
= render partial: 'layouts/footer'

app/views/member_organization_association/new.html.slim
doctype html
body.animsition[style="background-image: url(image_tag('/icons/pattern2.png')"]
  section.section-welcome.bg1-pattern.p-t-120.p-b-105[style="background-image: url(image_tag('/icons/pattern2.png')"]
    .container
      .row
        .col-md-6.p-t-45.p-b-30
          .wrap-text-welcome.t-center
            span.tit2.t-center
              |  Invite Members
            h3.tit3.t-center.m-b-35.m-t-5
              = @organization.name
            = form_tag('', method: :get, class: "flex-c-m flex-w flex-col-c-m-lg p-l-5 p-r-5") do
              wrap-input-signup.size17.bo2.bo-rad-10.bgwhite.pos-relative.txt10.m-10
                = text_field_tag :search, '', class: 'bo-rad-10 sizefull txt10 p-l-20', placeholder: "Email Adrress"
              = submit_tag 'Search', :name => nil, class: "btn3 flex-c-m size31 txt11 trans-0-4"
        .col-md-6.p-b-30
          .wrap-pic-welcome.size2.bo-rad-10.hov-img-zoom.m-l-r-auto
            - if @organization.image_url.present?
              = image_tag(@organization.image_url.url)
            - else
              = image_tag("default.png")
  section.section-chef.bgwhite.p-t-115.p-b-95
    .container.t-center
      span.tit2.t-center
        | Result
      .row
        - if @searched_members.present?
          - @searched_members.each do |member|
            .col-md-8.col-lg-4.m-l-r-auto.p-b-30
              .blo5.pos-relative.p-t-60
                .pic-blo5.size14.bo4.wrap-cir-pic.hov-img-zoom.ab-c-t
                  = link_to member_path(member)
                    - if member.image_url.present?
                      = image_tag(member.image_url)
                    - else
                      = image_tag("default.png")
                .text-blo5.size34.t-center.bo-rad-10.bo7.p-t-90.p-l-35.p-r-35.p-b-30
                  a.txt34.dis-block.p-b-6
                    = member.name
                  span.dis-block.t-center.txt35.p-b-25
                    = member.email
                  p.t-center
                    = member.text
                  = button_to "Invite", { :action => "create", :member_id => member.id, :organization_id => @organization.id }, { :class => "btn3 flex-c-m size31 txt11 trans-0-4", :style =>  "margin: auto;" }
= render partial: 'layouts/footer'