config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'index#show'
  devise_for :members, :controllers => { :omniauth_callbacks => "members/omniauth_callbacks" }
  devise_scope :member do
    get '/members/sign_out' => 'devise/sessions#destroy'
  end

  # For Member Pages
  resources :members, :only => [:show, :edit, :update]

  resources :organizations, :only => [:show]
  resources :organizations, :only => [:index] do
    resources :member_organization_association
    resources :lunch, only: %i[index create show] do
      resources :groups, only: %i[show edit update]
    end
  end

  # For Organization Admin Panel
  scope :organization_admin do
    resources :organizations, :only => [:create, :new, :edit, :update]
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  mount_uploader :image_url, ImageUploader
  has_many :members, through: :member_organization_associations
  has_many :member_organization_associations, dependent: :destroy

  validates :name, presence: true
  validates :url, presence: true
  validates :numbers_of_groups, presence: true
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[show edit update]
  before_action :authenticate_member!, only: [:index]
  before_action :load_associations, only: [:index]

  def index; end

  def show; end

  def new
    @organization = Organization.new
  end

  def edit
    redirect_to action: 'show' unless organizer?
  end

  def create
    @organization = Organization.create(organization_params)
    redirect_to action: 'show', id: @organization.id, flash: { success: 'Success!!' }
  end

  def update
    organization = Organization.find(params[:id])
    organization.update(organization_params)
    redirect_to action: 'show'
  end

  private

  def organizer?
    # OrganizerでないユーザーがOrganizationの情報を編集するのを防ぐ
    member_organization_association = MemberOrganizationAssociation.find_by(
      member_id: current_member.id,
      organization_id: @organization.id
    )
    member_organization_association ? member_organization_association.organizer : false
  end

  def load_associations
    @member = current_member
    @member_organization_associations = MemberOrganizationAssociation.find_by(member_id: @member.id)
    return nil if @member_organization_associations.nil?
    @organizations = Organization.where(id: @member_organization_associations.organization_id)
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization).permit(:name, :url, :image_url, :text, :numbers_of_groups)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/edit.html.slim
doctype html
body.animsition[style="background-image: url(image_tag('/icons/pattern2.png')"]
  section.section-welcome.bg1-pattern.p-t-120.p-b-105[style="background-image: url(image_tag('/icons/pattern2.png')"]
    .container
      .row
        .col-md-6.p-t-45.p-b-30
          .wrap-text-welcome.t-center
            span.tit2.t-center
              |  Organization
            h3.tit3.t-center.m-b-35.m-t-5
              |  Update
            = form_for(@organization, url: organization_path(@organization), html: {class: "wrap-form-booking"}) do |f|
              .size30.bo2.bo-rad-10.m-t-3.m-b-30
                = f.text_field :name, class: "bo-rad-10 sizefull txt10 p-l-20", placeholder: "Name"
              .size30.bo2.bo-rad-10.m-t-3.m-b-30
                = f.text_field :url, class: "bo-rad-10 sizefull txt10 p-l-20", placeholder: "URL"
              = f.text_area :text, class: "bo-rad-10 size29 bo2 txt10 p-l-20 p-t-15 m-b-10 m-t-40", placeholder: "Text"
              .input-group
                span.input-group-btn
                  span.btn3.flex-c-m.size31.txt11.trans-0-4[onclick="$(this).parent().find('input[type=file]').click();"]
                    | Image upload
                  = f.file_field :image_url, onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;"
                span.form-control
              br
              .row
                .col-md-6
                  span.txt22.m-t-20
                    | Numbers of groups:
                .col-md-6
                  = f.select :numbers_of_groups, options_for_select((1..10).to_a), {}, class: "form-control"
              br
              = f.submit "Update", class: "btn3 flex-c-m size31 txt11 trans-0-4"
        .col-md-6.p-b-30
          .wrap-pic-welcome.size2.bo-rad-10.hov-img-zoom.m-l-r-auto
            - if @organization.image_url.present?
              = image_tag(@organization.image_url.url)
            - else
              = image_tag("default.png")
= render partial: 'layouts/footer'

app/views/organizations/index.html.slim
doctype html
body.animsition[style="background-image: url(images/icons/pattern2.png)"]
  .container
    .row
      .col-md-4.p-t-30
        - if @organizations.present?
          - @organizations.each do |organization|
            .blo1
              .wrap-pic-blo1.bo-rad-10.hov-img-zoom
                - if organization.image_url.present?
                  = link_to image_tag(organization.image_url.url), organization_lunch_index_path(organization)
                - else
                  = link_to image_tag("default.png"), organization_lunch_index_path(organization)
              .wrap-text-blo1.p-t-35
                = link_to organization.name, organization_lunch_index_path(organization), class: "txt5 color0-hov trans-0-4 m-b-13"
                p.m-b-20
                  = organization.text
                = link_to 'Go To Lunch', organization_lunch_index_path(organization), class: "txt4"
                i.fa.fa-long-arrow-right.m-l-10[aria-hidden="true"]

app/views/organizations/new.html.slim
doctype html
body.animsition[style="background-image: url(image_tag('/icons/pattern2.png')"]
  section.section-welcome.bg1-pattern.p-t-120.p-b-105[style="background-image: url(image_tag('/icons/pattern2.png')"]
    .container
    .row
      .col-md-6.p-t-45.p-b-30
        .wrap-text-welcome.t-center
          span.tit2.t-center
            |  Organization
          h3.tit3.t-center.m-b-35.m-t-5
            |  Registration
          = form_for(@organization, url: organizations_path, html: {class: "wrap-form-booking"}) do |f|
            .size30.bo2.bo-rad-10.m-t-3.m-b-30
              = f.text_field :name, class: "bo-rad-10 sizefull txt10 p-l-20", placeholder: "name"
            .size30.bo2.bo-rad-10.m-t-3.m-b-30
              = f.text_field :url, class: "bo-rad-10 sizefull txt10 p-l-20", placeholder: "url"
            = f.text_area :text, class: "bo-rad-10 size29 bo2 txt10 p-l-20 p-t-15 m-b-10 m-t-40"
            .input-group
              span.input-group-btn
                span.btn3.flex-c-m.size31.txt11.trans-0-4[onclick="$(this).parent().find('input[type=file]').click();"]
                  | Image upload
                = f.file_field :image_url, onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;"
              span.form-control
            br
            = f.submit "Registration", class: "btn3 flex-c-m size31 txt11 trans-0-4"

app/views/organizations/show.html.slim
doctype html
body.animsition[style="background-image: url(images/icons/pattern2.png)"]
  section.section-welcome.bg1-pattern.p-t-120.p-b-105
    .container
      .row
        .col-md-6.p-t-45.p-b-30
          .wrap-text-welcome.t-center
            span.tit2.t-center
              |  Organization
            h3.tit3.t-center.m-b-35.m-t-5
              = @organization.name
            p.t-center.m-b-22.size3.m-l-r-auto
              = @organization.text
            p.t-center.m-b-22.size3.m-l-r-auto
              = link_to @organization.url, @organization.url
            p.t-center.m-b-22.size3.m-l-r-auto
              = link_to "Members", organization_member_organization_association_index_path(@organization), class: "btn3 flex-c-m size31 txt11 trans-0-4", style: "margin: auto;"
        .col-md-6.p-b-30
          .wrap-pic-welcome.size2.bo-rad-10.hov-img-zoom.m-l-r-auto
            - if @organization.image_url.present?
              = image_tag(@organization.image_url.url)
            - else
              = image_tag("default.png")
= render partial: 'layouts/footer'