config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'index#show'
  devise_for :members, :controllers => { :omniauth_callbacks => "members/omniauth_callbacks" }
  devise_scope :member do
    get '/members/sign_out' => 'devise/sessions#destroy'
  end

  # For Member Pages
  resources :members, :only => [:show, :edit, :update]

  resources :organizations, :only => [:show]
  resources :organizations, :only => [:index] do
    resources :member_organization_association
    resources :lunch, only: %i[index create show] do
      resources :groups, only: %i[show edit update]
    end
  end

  # For Organization Admin Panel
  scope :organization_admin do
    resources :organizations, :only => [:create, :new, :edit, :update]
  end
end

app/models/lunch.rb
class Lunch < ApplicationRecord
  belongs_to :organization
  has_many :groups, dependent: :destroy

  validates :organization_id, presence: true, numericality: true

  def create_group_with_rank!(rank)
    groups.create!(rank: rank)
  end
end

app/controllers/lunch_controller.rb
class LunchController < ApplicationController
  before_action :set_resources

  def index; end

  def create
    return redirect_to action: 'index' if @members.nil?
    members = @members.shuffle
    numbers_of_groups = @organization.numbers_of_groups
    create_lunch(members, numbers_of_groups)
  end

  def show
    @lunch = Lunch.find(params[:id])
    @groups = Group.where(lunch_id: params[:id])
  end

  private

  def create_lunch(members, numbers_of_groups)
    return redirect_to({ action: :index }, notice: 'Numbers_of_groups is Zero.') if numbers_of_groups.zero?
    ActiveRecord::Base.transaction do
      lunch = Lunch.create(organization_id: @organization.id)
      create_groups(lunch, numbers_of_groups, members)
    end
    redirect_to({ action: :index }, notice: 'Success!!')
  end

  def create_groups(lunch, numbers_of_groups, members)
    groups = []
    numbers_of_groups.times do |num|
      group = lunch.create_group_with_rank!(num)
      groups.push(group)
    end
    split_members(groups, numbers_of_groups, members)
  end

  def split_members(groups, numbers_of_groups, members)
    # 1人のみなどの端数のグループが発生しないよう、Member毎にをグループ分けの処理に渡す。
    members.each_with_index do |member, i|
      rank = i % numbers_of_groups
      assign_groups(groups, member, rank)
    end
  end

  def assign_groups(groups, member, rank)
    # MemberにGroupを割り当てる
    group = groups[rank]
    group.create_member_group_association!(member)
  end

  def set_resources
    @organization = Organization.find(params[:organization_id])
    @lunches = Lunch.where(organization_id: params[:organization_id])
    @members = Member.includes(:organizations).where(organizations: { id: @organization.id })
  end
end

app/helpers/lunch_helper.rb
module LunchHelper
end

app/views/lunch/index.html.slim
doctype html
= render :partial => 'layouts/header'
body.animsition[style="background-image: url(images/icons/pattern2.png)"]
  section.section-ourmenu.bg2-pattern.p-t-115.p-b-120
    .container
      .title-section-ourmenu.t-center.m-b-22
        span.tit2.t-center
          |  History
        h3.tit5.t-center.m-t-2
          |  Past Lunch
        - @lunches.each do |lunch|
          .text-blo4.p-t-33
            h4.p-b-16
              = link_to lunch.created_at.strftime('%Y-%m-%d'), organization_lunch_path(@organization.id, lunch.id), class: "tit9"
              i.fa.fa-long-arrow-right.m-l-10[aria-hidden="true"]
  section.section-video.parallax100[style="background-image: url(../../images/bg-cover-video-02.jpg);"]
    .content-video.t-center.p-t-225.p-b-250
      span.tit2.p-l-15.p-r-15
        |  New Lunch
      h3.tit4.t-center.p-l-15.p-r-15.p-t-3
        |  Create
      .btn-play.ab-center.size16.hov-pointer.m-l-r-auto.m-t-43.m-b-33[data-toggle="modal" data-target="#modal-video-01"]
        .flex-c-m.sizefull.bo-cir
          = button_to "Start!!", { :controller => "lunch", :action => "create" }, { :class => "btn1 flex-c-m size1 txt3 trans-0-4" }
  section.section-welcome.bg1-pattern.p-t-120.p-b-105
    .container
      .row
        .col-md-6.p-t-45.p-b-30
          .wrap-text-welcome.t-center
            span.tit2.t-center
              |  Organization
            h3.tit3.t-center.m-b-35.m-t-5
              = link_to @organization.name, organization_path(@organization), class: "tit3 t-center m-b-35 m-t-5"
            p.t-center.m-b-22.size3.m-l-r-auto
              = @organization.text
        .col-md-6.p-b-30
          .wrap-pic-welcome.size2.bo-rad-10.hov-img-zoom.m-l-r-auto
            - if @organization.image_url.present?
              = link_to image_tag(@organization.image_url.url), organization_path(@organization)
            - else
              = link_to image_tag("default.png"), organization_path(@organization)
= render partial: 'layouts/footer'

app/views/lunch/show.html.slim
= render :partial => 'layouts/header'
doctype html
html[lang="en"]
  body.animsition
    section.bg-title-page.flex-c-m.p-t-160.p-b-80.p-l-15.p-r-15[style="background-image: url(../../../../images/bg-title-page-02.jpg);"]
      h2.tit6.t-center
        = @lunch.created_at.strftime('%Y-%m-%d(%a)')
    .section-gallery.p-t-118.p-b-100
      .wrap-gallery.isotope-grid.flex-w.p-l-25.p-r-25
        - @groups.each do |group|
          .item-gallery.isotope-item.bo-rad-10.hov-img-zoom.events.guests
            - if group.image_url.present?
              = image_tag(group.image_url.url)
            - else
              = image_tag("default.png")
            .overlay-item-gallery.trans-0-4.flex-c-m
              = link_to group.rank+1, organization_lunch_group_path(id: group.id, lunch_id: @lunch.id), class: "btn-show-gallery flex-c-m fa fa-search"
= render partial: 'layouts/footer'