config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'index#show'
  devise_for :members, :controllers => { :omniauth_callbacks => "members/omniauth_callbacks" }
  devise_scope :member do
    get '/members/sign_out' => 'devise/sessions#destroy'
  end

  # For Member Pages
  resources :members, :only => [:show, :edit, :update]

  resources :organizations, :only => [:show]
  resources :organizations, :only => [:index] do
    resources :member_organization_association
    resources :lunch, only: %i[index create show] do
      resources :groups, only: %i[show edit update]
    end
  end

  # For Organization Admin Panel
  scope :organization_admin do
    resources :organizations, :only => [:create, :new, :edit, :update]
  end
end

app/views/layouts/_flash_messages.html.slim
- flash.each do |message_type, message|
    div class="alert.alert-#{message_type}"
      = "#{message}"

app/views/layouts/_footer.html.slim
footer.bg1
  .container.p-t-40.p-b-70
    .row
      .col-sm-6.col-md-4.p-t-50
        h4.txt13.m-b-33
          |  Contact Me 
        ul.m-b-70
          li.txt14.m-b-14
            i.fa.fa-map-marker.fs-16.dis-inline-block.size19[aria-hidden="true"]
            |  Tokyo, Japan 
          li.txt14.m-b-14
            i.fa.fa-envelope.fs-13.dis-inline-block.size19[aria-hidden="true"]
            |  teru_fukumoto@outlook.jp 
      .col-sm-6.col-md-4.p-t-50
        h4.txt13.m-b-32
          |  My Profle 
        ul
          li.txt14
            |  Name: Teruhisa Fukumoto 
          li.txt14
            |  Country: Japan 
          li.txt14
            |  Birth: 1992/03/24 
          li.txt14
            |  Gender: Male 
          li.txt14
            |  Organization: VPoE & Engineer at ZEALS 
      .col-sm-6.col-md-4.p-t-50
        h4.txt13.m-b-33
          |  Latest Social Account 
        .m-b-25
          span.fs-13.color2.m-r-5
            i.fa.fa-twitter[aria-hidden="true"]
          a.txt15[href="https://twitter.com/terry_i_"]
            |  @terry_i_ 
          p.txt14.m-b-18
            |  My Twitter account 
          span.fs-13.color2.m-r-5
            i.fa.fa-facebook-square
          a.txt15[href="https://www.facebook.com/teruhisa.fukumoto"]
            |  Teruhisa Fukumoto 
          p.txt14.m-b-18
            |  My facebook account 
          span.fs-13.color2.m-r-5
            i.fa.fa-medium
          a.txt15[href="https://medium.com/@teruhisafukumoto"]
            |  @teruhisafukumoto 
          p.txt14.m-b-18
            |  My Blog(Medium) 
          span.fs-13.color2.m-r-5
            i.fa.fa-github-square
          a.txt15[href="https://github.com/f-teruhisa"]
            |  f-teruhisa 
          p.txt14.m-b-18
            |  Github 
  .end-footer.bg2
    .container
      .flex-sb-m.flex-w.p-t-22.p-b-22
        .txt17.p-r-20.p-t-5.p-b-5[style="margin:auto;"]
          |  Copyright © 2018 All rights reserved | This template is made with 
          i.fa.fa-heart
          |  by 
          a[href="https://colorlib.com" target="_blank"]
            | Colorlib

app/views/layouts/_header.html.slim
header
  .wrap-menu-header.gradient1.trans-0-4
    .container.h-full
      .wrap_header.trans-0-3
        .logo
          = link_to root_path
            = image_tag("/images/icons/logo.png")
        .wrap_menu.p-l-45.p-l-0-xl
          nav.menu
            ul.main_menu
              li
                - if member_signed_in?
                  = link_to "My Page", member_path(current_member)
              li
                - if member_signed_in?
                  = link_to "Sign Out", members_sign_out_path, method: :delete
        .social.flex-w.flex-l-m.p-r-20
          a[href="https://github.com/f-teruhisa/QuartZ"]
            i.fa.fa-github-square[aria-hidden="true"]
          a[href="https://www.facebook.com/teruhisa.fukumoto"]
            i.fa.fa-facebook.m-l-21[aria-hidden="true"]
          a[href="https://twitter.com/terry_i_"]
            i.fa.fa-twitter.m-l-21[aria-hidden="true"]

app/views/layouts/_sidebar.html.slim
aside.sidebar.trans-0-4
  button.btn-hide-sidebar.ti-close.color0-hov.trans-0-4
  ul.menu-sidebar.p-t-95.p-b-70
    li.t-center.m-b-13
      a.txt19[href="index.html"]
        | Home
    li.t-center.m-b-13
      a.txt19[href="menu.html"]
        | Menu
    li.t-center.m-b-13
      a.txt19[href="gallery.html"]
        | Gallery
    li.t-center.m-b-13
      a.txt19[href="about.html"]
        | About
    li.t-center.m-b-13
      a.txt19[href="blog.html"]
        | Blog
    li.t-center.m-b-33
      a.txt19[href="contact.html"]
        | Contact
    li.t-center
      a.btn3.flex-c-m.size13.txt11.trans-0-4.m-l-r-auto[href="reservation.html"]
        |  Reservation
  .gallery-sidebar.t-center.p-l-60.p-r-60.p-b-40
    h4.txt20.m-b-33
      |  Gallery
    .wrap-gallery-sidebar.flex-w
      a.item-gallery-sidebar.wrap-pic-w[href="images/photo-gallery-01.jpg" data-lightbox="gallery-footer"]
        img[src="images/photo-gallery-thumb-01.jpg" alt="GALLERY"]
      a.item-gallery-sidebar.wrap-pic-w[href="images/photo-gallery-02.jpg" data-lightbox="gallery-footer"]
        img[src="images/photo-gallery-thumb-02.jpg" alt="GALLERY"]
      a.item-gallery-sidebar.wrap-pic-w[href="images/photo-gallery-03.jpg" data-lightbox="gallery-footer"]
        img[src="images/photo-gallery-thumb-03.jpg" alt="GALLERY"]
      a.item-gallery-sidebar.wrap-pic-w[href="images/photo-gallery-05.jpg" data-lightbox="gallery-footer"]
        img[src="images/photo-gallery-thumb-05.jpg" alt="GALLERY"]
      a.item-gallery-sidebar.wrap-pic-w[href="images/photo-gallery-06.jpg" data-lightbox="gallery-footer"]
        img[src="images/photo-gallery-thumb-06.jpg" alt="GALLERY"]
      a.item-gallery-sidebar.wrap-pic-w[href="images/photo-gallery-07.jpg" data-lightbox="gallery-footer"]
        img[src="images/photo-gallery-thumb-07.jpg" alt="GALLERY"]
      a.item-gallery-sidebar.wrap-pic-w[href="images/photo-gallery-09.jpg" data-lightbox="gallery-footer"]
        img[src="images/photo-gallery-thumb-09.jpg" alt="GALLERY"]
      a.item-gallery-sidebar.wrap-pic-w[href="images/photo-gallery-10.jpg" data-lightbox="gallery-footer"]
        img[src="images/photo-gallery-thumb-10.jpg" alt="GALLERY"]
      a.item-gallery-sidebar.wrap-pic-w[href="images/photo-gallery-11.jpg" data-lightbox="gallery-footer"]
        img[src="images/photo-gallery-thumb-11.jpg" alt="GALLERY"]

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | QuartZ
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag('favicon.ico')
  body
    = render partial: 'layouts/flash_messages'
    = yield
    = stylesheet_link_tag "bootstrap.min"
    = stylesheet_link_tag "font-awesome"
    = stylesheet_link_tag "themify-icons"
    = stylesheet_link_tag "animate"
    = stylesheet_link_tag "select2"
    = stylesheet_link_tag "slick"
    = stylesheet_link_tag "index"
    = javascript_include_tag "jquery-3.2.1.min"
    = javascript_include_tag "animsition"
    = javascript_include_tag "popper"
    = javascript_include_tag "bootstrap.min"
    = javascript_include_tag "select2"
    = javascript_include_tag "slick"
    = javascript_include_tag "slick-custom"
    = javascript_include_tag "index"

app/views/layouts/error.html.slim
doctype html
html
  head
    title
      | QuartZ
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag('favicon.ico')
  body
    = yield
    = stylesheet_link_tag "bootstrap.min"
    = stylesheet_link_tag "font-awesome"
    = stylesheet_link_tag "themify-icons"
    = stylesheet_link_tag "animate"
    = stylesheet_link_tag "select2"
    = stylesheet_link_tag "slick"
    = stylesheet_link_tag "index"
    = javascript_include_tag "jquery-3.2.1.min"
    = javascript_include_tag "animsition"
    = javascript_include_tag "popper"
    = javascript_include_tag "bootstrap.min"
    = javascript_include_tag "select2"
    = javascript_include_tag "slick"
    = javascript_include_tag "slick-custom"
    = javascript_include_tag "index"